blog/urls.py
# polls 폴더에 urls.py가 업어서 새로 생성

from django.urls import path, re_path

from . import views

app_name = "blog"

urlpatterns = [
    path("", views.PostLV.as_view(), name="index"),    
    path("post/", views.PostLV.as_view(), name="post_list"),    
    # path("post/<slug:slug>", views.PostDV.as_view(), name="post_detail"),    
    re_path(r'post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name="post_detail"), 
    
    # Example: /blog/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive'),

    # Example: /blog/archive/2019/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),

    # Example: /blog/archive/2019/nov/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),

    # Example: /blog/archive/2019/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),

    # Example: /blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
    
    path('search/', views.SearchFormView.as_view(), name='search'),
]

bookmark/urls.py
# polls 폴더에 urls.py가 업어서 새로 생성

from django.urls import path

from . import views

app_name = "bookmark"

urlpatterns = [
    path("", views.BookmarkLV.as_view(), name="index"),
    path("<int:pk>/", views.BookmarkDV.as_view(), name="detail"),    
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from config.views import HomeView
from django.conf.urls.static import static
from django.conf import settings
from config.views import UserCreateView, UserCreateDoneTV
from django.contrib.auth import views as auth_views # 추가
urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path('admin/', admin.site.urls),
    path("bookmark/", include("bookmark.urls")),
    path("blog/", include("blog.urls")),    
    path("photo/", include("photo.urls")),    
    # 신규 작성
    path('accounts/', include('django.contrib.auth.urls')), 
    path('accounts/register/',UserCreateView.as_view(), name='register'),
    path('accounts/register/done/',UserCreateDoneTV.as_view(), name='register_done'),
    # path('logout/', auth_views.LoginView.as_view(next_page='home'), name='logout'), # 추가
    path('my_page/', include('my_page.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

bookmark/models.py
from django.db import models

# Create your models here.
# title, url


class Bookmark(models.Model):
    title = models.CharField('TITLE', max_length=100, blank=True)
    url = models.URLField('URL', unique=True)
    def __str__(self):
        # return self.title
        # return self.url
        return self.title
    

bookmark/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from bookmark.models import Bookmark
# Create your views here.

class BookmarkLV(ListView):
    model=Bookmark

    # template_name="bookmark/bookmark_list.html" #appname/model_name_list.html
    # context_object_name = "object_list" # object_list
    
class BookmarkDV(DetailView):
    model=Bookmark
     # template_name="bookmark/bookmark_detail.html" #appname/model_name_detail.html
     # context_object_name = "object" # object

bookmark/templates/bookmark/bookmark_detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Bookmark App{% endblock %}

{% block content %}

<h3>TITLE : {{object.title}}</h3>

<h5>URL : <a href="{{object.url}}"> {{object.url}} </a> </h5>
{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Bookmark App{% endblock %}

{% block content %}

<h3>Bookmark List</h3>
<br>
<ul class="list-group ">
    {% for bookmark in object_list %}
    <li class="list-group-item"><a href="{% url 'bookmark:detail' bookmark.id %}">{{ bookmark.title }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

bookmark/templates/bookmark/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body class="container m-1">
    <a href="#" class="btn btn-success btn-lg">Click</a>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>