blog/urls.py
# polls 폴더에 urls.py가 업어서 새로 생성

from django.urls import path, re_path

from . import views

app_name = "blog"

urlpatterns = [
    path("", views.PostLV.as_view(), name="index"),    
    path("post/", views.PostLV.as_view(), name="post_list"),    
    # path("post/<slug:slug>", views.PostDV.as_view(), name="post_detail"),    
    re_path(r'post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name="post_detail"), 
    
    # Example: /blog/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive'),

    # Example: /blog/archive/2019/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),

    # Example: /blog/archive/2019/nov/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),

    # Example: /blog/archive/2019/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),

    # Example: /blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
    
    path('search/', views.SearchFormView.as_view(), name='search'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from config.views import HomeView
from django.conf.urls.static import static
from django.conf import settings
from config.views import UserCreateView, UserCreateDoneTV
from django.contrib.auth import views as auth_views # 추가
urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path('admin/', admin.site.urls),
    path("bookmark/", include("bookmark.urls")),
    path("blog/", include("blog.urls")),    
    path("photo/", include("photo.urls")),    
    # 신규 작성
    path('accounts/', include('django.contrib.auth.urls')), 
    path('accounts/register/',UserCreateView.as_view(), name='register'),
    path('accounts/register/done/',UserCreateDoneTV.as_view(), name='register_done'),
    # path('logout/', auth_views.LoginView.as_view(next_page='home'), name='logout'), # 추가
    path('my_page/', include('my_page.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse 
from taggit.managers import TaggableManager # 추가
# Create your models here.
# id, title, slug, description, content, create_dt, modify_dt

class Post(models.Model):
    title = models.CharField(verbose_name='TITLE', max_length=50)
    slug = models.SlugField(verbose_name="SLUG", unique=True, allow_unicode=True, help_text="one word for title alias.")
    description = models.CharField("DESCRIPTION", max_length=100, blank=True, help_text="simple text")
    content = models.TextField("CONTENT")
    create_dt = models.DateTimeField("CREATE DATE", auto_now_add=True)
    modify_dt = models.DateTimeField("MODIFY DATE", auto_now=True)
    tags = TaggableManager(blank=True) # 추가

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'blog_posts'
        ordering=('-modify_dt',)
        
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.slug, ))
    def get_previous(self):
        return self.get_previous_by_modify_dt()
    def get_next(self):
        return self.get_next_by_modify_dt()
    
"""
# Question과 Choice 구조와 같습니다.
class Comment(models.Model):
    # user
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment = models.CharField(max_length=200)
    # date ....
"""   

blog/forms.py
from django import forms

class PostSearchForm(forms.Form):
    search_word = forms.CharField(label="Search Word")
    # date_val = forms.DateField(label="날짜정보")

blog/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.http import HttpResponse
from django.shortcuts import render
from blog.models import Post
from django.views.generic import ListView, DetailView, ArchiveIndexView, YearArchiveView, MonthArchiveView, DayArchiveView, TodayArchiveView
from django.views.generic import TemplateView
from django.conf import settings
# Create your views here.

class PostLV(ListView):
    model = Post
    template_name = "blog/post_all.html" 
    context_object_name = 'posts' 
    paginate_by = 3
    # def get_queryset(self):
    #     return Post.objects.all()

def dummpy_post(request):
    objects = Post.objects.all()
    context = {
        'posts' : objects
    }
    return render(request, "blog/post_all.html", context)

class PostDV(DetailView):
    model=Post
    template_name="blog/post_detail.html"
    # get_queryset - > get_object
    # def get_object(self):pass
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['disqus_short'] = f"{settings.DISQUS_SHORTNAME}"
        context['disqus_id'] = f"post-{self.object.id}-{self.object.slug}"
        context['disqus_url'] = f"{settings.DISQUS_MY_DOMAIN}{self.object.get_absolute_url()}"
        context['disqus_title'] = f"{self.object.slug}"
        return context        



#--- ArchiveView
class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'modify_dt'
    template_name = "blog/post_archive.html"


class PostYAV(YearArchiveView):
    model = Post
    date_field = 'modify_dt'
    make_object_list = True
    template_name = "blog/post_archive_year.html"



class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'modify_dt'
    template_name = "blog/post_archive_month.html"

class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_dt'
    template_name = "blog/post_archive_day.html"

class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_dt'
    template_name = "blog/post_archive_day.html"

class TagCloudTV(TemplateView):
    template_name="taggit/taggit_cloud.html"

class TaggedObjectLV(ListView):
    template_name='taggit/taggit_post_list.html'
    model = Post
    def get_queryset(self):
        return Post.objects.filter(tags__name=self.kwargs.get('tag'))
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tagname'] = self.kwargs['tag']
        return context
    
from django.views.generic import FormView
from blog.forms import PostSearchForm
from django.db.models import Q

class SearchFormView(FormView):
    form_class = PostSearchForm
    template_name = 'blog/post_search.html'

    def form_valid(self, form: Any) -> HttpResponse:
        # 검색어 확인
        searchWord = form.cleaned_data['search_word']
        # Q를 통해 검색하고
        post_list = Post.objects.filter(Q(title__icontains=searchWord) | Q(description__icontains=searchWord) | Q(content__icontains=searchWord)).distinct()
        # 결과를 담아
        context = {}
        context['form'] = form
        context['search_term'] = searchWord
        context['object_list'] = post_list
        # 페이지에 전달
        return render(self.request, self.template_name, context)

blog/templates/blog/post_all.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Post All{% endblock %}

{%block content%}
<h1>BLOG POST LIST</h1>
<br>
<div class="row">
    사용자 정보 {{user}}
    {% for post in posts %}
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">{{post.title |truncatechars:13}}</h5>
            <h6 class="card-subtitle mb-2 text-body-secondary">{{post.content|truncatechars:20}}</h6>
            <a href="{% url 'blog:post_detail' post.slug %}" class="card-link">Detail link</a>
        </div>
    </div>
    {% endfor %}
</div>
<br>

<div>
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a href="?page={{ page_obj.previous_page_number }}" class="page-link">PreviousPage</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a href="#" class="page-link">PreviousPage</a>
            </li>
            {% endif %}
            <li class="page-item"><a class="page-link" href="#">Page {{ page_obj.number }} of {{page_obj.paginator.num_pages }}</a></li>

            {% if page_obj.has_next %}
            <li class="page-item">
                <a href="?page={{ page_obj.next_page_number }}" class="page-link">NextPage</a>
                {% else %}
            <li class="page-item disabled">
                <a href="#" class="page-link">NextPage</a>
            </li>
            </li>
            {% endif %}
        </ul>
    </nav>
</div>
{% endblock %}

blog/templates/blog/post_archive.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Post All{% endblock %}

{%block content%}
<h1>Archive List {% now "Y m d" %}</h1>

<ul>
    {% for date in date_list %}
    <li style="display: inline;"><a href="{% url 'blog:post_year_archive' date|date:'Y' %}"> Year-{{date|date:'Y'}} </a>
    </li>
    {% endfor %}
</ul>

<br>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{post.modify_dt | date:"Y-m-d"}}
            <a href="{{post.get_absolute_url}}">{{post.title}}</a>
        </li>
        {% endfor %}
    </ul>
</div>
{%endblock%}

blog/templates/blog/post_archive_day.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Post All{% endblock %}

{%block content%}
<h1>Post Archives for {{ day|date:"N d, Y" }}</h1>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>
</div>

{%endblock%}

blog/templates/blog/post_archive_month.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Post All{% endblock %}

{%block content%}
<h1>Post Archives for {{ month|date:"N, Y" }}</h1>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
        </li>
        {% endfor %}
    </ul>
</div>
{%endblock%}

blog/templates/blog/post_archive_year.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Post All{% endblock %}

{%block content%}
<h1>Post Archives for {{year|date:"Y"}}</h1>


<ul>
    {% for date in date_list %}
    <li style="display: inline;"><a href="{% url 'blog:post_month_archive' date|date:'Y' date|date:'b'%}">
            Year-{{date|date:'F'}}</a></li>
    {% endfor %}
</ul>

{# m : 04, F : April, M : Apr, b : apr #}

<br>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{post.modify_dt | date:"Y-m-d"}}
            <a href="{{post.get_absolute_url}}">{{post.title}}</a>
        </li>
        {% endfor %}
    </ul>
</div>
{%endblock%}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Post Detail{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-8 mx-auto">
            <h1 class="mb-4">{{ post.title }}</h1>
            <p class="text-muted">게시일: {{ object.modify_dt|date:"j F Y" }}</p>
            <div class="post-content mt-4">
                {{ object.content|linebreaks }}
            </div>
        </div>
    </div>

    <br>
    <div>
        <b>TAGS</b> <i class="fas fa-tag"></i>
        {% load taggit_templatetags2_tags %}
        {% get_tags_for_object object as "tags" %}
        {% for tag in tags %}
        <a href="{% url 'blog:tagged_object_list' tag.name %}">{{tag.name}}</a>
        {% endfor %}
        &emsp;
        <a href="{% url 'blog:tag_cloud' %}"> <span class="btn btn-info btn-sm">TagCloud</span> </a>
    </div>

    <br>
    <div id="disqus_thread">
    </div>
    {# <p class="container">
        {% if object.get_previous %}
        <a href="{{ object.get_previous.get_absolute_url }}" title="View previous post">
            &laquo;-- {{ object.get_previous }}
        </a>
        {% endif %}
        {% if object.get_next %}
        | <a href="{{ object.get_next.get_absolute_url }}" title="View next post">
            {{ object.get_next }} --&raquo;
        </a>
        {% endif %}
    </p> #}
</div>
{%endblock%}
{% block extra-script %}
<script>
    /**
    *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION
    *  BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
    *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT:
    *  https://disqus.com/admin/universalcode/#configuration-variables*/

    var disqus_config = function () {
        this.page.identifier = '{{ disqus_id }}';
        this.page.url = '{{ disqus_url }}';
        this.page.title = '{{ disqus_title }}';
    };

    (function () { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://{{ disqus_short }}.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by
        Disqus.</a></noscript>
{% endblock %}

blog/templates/blog/post_list.html
<h1>BLOG POST LIST</h1>
<br>
{% for post in posts %}
<h3><a href="">{{post.title}}</a> </h3>
{{post.modify_dt | date:"Y년 N d일" }}
<p>{{post.content}}</p>
{% endfor %}

<br>

<div>
    <span>
        {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">PreviousPage</a>
        {% endif %}

        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">NextPage</a>
        {% endif %}
    </span>

</div>

blog/templates/blog/post_search.html
{% extends "base.html" %}

{% block title %}Post_Search.html{% endblock %}
{% block content %}
<h1>Blog Search</h1>
<br>
<form action="." method="post">
    {% csrf_token %}
    <div class="input-group mb-3">
        {{form.as_table}}
    </div>
    <input type="submit" value="검색" class="btn btn-primary">
</form>

<br><br>
{% if object_list %}
{% for post in object_list %}
<h2><a href="{{post.get_absolute_url}}">{{post.title}}</a></h2>
{{post.modify_date|date:"Y N d"}}
<p>{{post.content}}</p>
{% endfor %}
{% elif search_term %}
<b>Search Word <i>{{search_term}}</i>으로 검색했는데 안나왔어요</b>
{% endif %}
{% endblock %}