blog/urls.py
# polls 폴더에 urls.py가 업어서 새로 생성

from django.urls import path, re_path

from . import views

app_name = "blog"

urlpatterns = [
    path("", views.PostLV.as_view(), name="index"),    
    path("post/", views.PostLV.as_view(), name="post_list"),    
    # path("post/<slug:slug>", views.PostDV.as_view(), name="post_detail"),    
    re_path(r'post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name="post_detail"), 
    
    # Example: /blog/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive'),

    # Example: /blog/archive/2019/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),

    # Example: /blog/archive/2019/nov/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),

    # Example: /blog/archive/2019/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),

    # Example: /blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
    
    path('search/', views.SearchFormView.as_view(), name='search'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from config.views import HomeView
from django.conf.urls.static import static
from django.conf import settings
from config.views import UserCreateView, UserCreateDoneTV
from django.contrib.auth import views as auth_views # 추가
urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path('admin/', admin.site.urls),
    path("bookmark/", include("bookmark.urls")),
    path("blog/", include("blog.urls")),    
    path("photo/", include("photo.urls")),    
    # 신규 작성
    path('accounts/', include('django.contrib.auth.urls')), 
    path('accounts/register/',UserCreateView.as_view(), name='register'),
    path('accounts/register/done/',UserCreateDoneTV.as_view(), name='register_done'),
    # path('logout/', auth_views.LoginView.as_view(next_page='home'), name='logout'), # 추가
    path('my_page/', include('my_page.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

photo/urls.py
# polls 폴더에 urls.py가 업어서 새로 생성

from django.urls import path, include
from . import views
from rest_framework.routers import DefaultRouter
from .views import AlbumViewSet, PhotoViewSet

app_name = "photo"

router = DefaultRouter()
router.register(r"album", AlbumViewSet)
router.register(r"photo", PhotoViewSet)

urlpatterns = [    
    path("", views.AlbumLV.as_view(), name="index"),
    path("album", views.AlbumLV.as_view(), name="album_list"),
    path("album/<int:pk>", views.AlbumDV.as_view(), name="album_detail"),
    path("photo/<int:pk>", views.PhotoDV.as_view(), name="photo_detail"),
    path('', include(router.urls)),
]

photo/models.py
from django.db import models
from photo.fields import ThumbnailImageField
from django.urls import reverse 

# Create your models here.
class Album(models.Model):
    name = models.CharField(max_length=20)
    description = models.CharField('One Line Description', max_length=100, blank=True)

    class Meta:
        ordering = ('name',)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('photo:album_detail', args=(self.id, ))

class Photo(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    title = models.CharField('TITLE', max_length=30)
    description = models.TextField('Photo Description', blank=True)
    image = ThumbnailImageField('IMAGE', upload_to='photo/%Y/%m')
    
    # image_path = 
    upload_dt = models.DateTimeField("UPLOAD DATE", auto_now_add=True)
    class Meta:
        ordering = ('title',)
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=(self.id, ))

photo/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Album, Photo
from rest_framework import viewsets
from .serializers import AlbumSerializer, PhotoSerializer
# Create your views here.

class AlbumLV(ListView):
    model=Album
    

class AlbumDV(DetailView):
    model=Album
    template_name='photo/album_detail.html'
    # pk를 통해서 특정 앨범만 가져온다

class PhotoDV(DetailView):
    model=Photo
    template_name='photo/photo_detail.html'


# ViewSets define the view behavior.
class AlbumViewSet(viewsets.ModelViewSet):
    queryset = Album.objects.all()
    serializer_class = AlbumSerializer


class PhotoViewSet(viewsets.ModelViewSet):
    queryset = Photo.objects.all()
    serializer_class = PhotoSerializer

photo/templates/photo/album_detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Album Detail{% endblock %}

{%block content%}
<div class="mt-5">
    <span class="h2">{{object.name}}</span>
    <span class="h5">{{object.description}}</span>
</div>

<div class="row"> 
    {% for photo in object.photo_set.all|slice:":4" %} 
    <div class="ml-5 col-sm-3"> 
        <div class="thumbnail">
            <a href="{{ photo.get_absolute_url }}">
                <img src="{{ photo.image.thumb_url }}" style="width: 100%;">
            </a>
        </div>
        <ul class="list-group-flush">
            <li class="h5 list-group-item list-group-item-success">{{photo.title}}</li>
            <li class="list-group-item">{{photo.description}}</li>
            
        </ul>
    </div>
    {% endfor %} 
</div>
{% endblock %}

photo/templates/photo/album_list.html
{% extends "base.html" %} 

{% block title %}album_list.html{% endblock %} 

{% block extra-style %}
<style>
.thumbnail {
    border: 3px solid #ccc;
}
</style>
{% endblock %}

{% block content %} 

    {% for item in object_list %} 

    <div class="mt-5"> 
        <a class="h2" href="{% url 'photo:album_detail' item.id %}">
            {{ item.name }}</a>&emsp;
        <span class="font-italic h5">{{ item.description }}</span>
    </div>

    <hr style="margin: 0 0 20px 0;"> 

    <div class="row"> 
        {% for photo in item.photo_set.all|slice:":4" %} 
        <div class="ml-5 col-sm-3"> 
            <div class="thumbnail">
                 <a href="{{ photo.get_absolute_url }}"> 

                {# <a href="{% url 'photo:photo_detail' photo.id">#}
                    <img src="{{ photo.image.thumb_url }}" style="width: 100%;">
                </a>
            </div>
        </div>
        {% endfor %} 
    </div>

    {% endfor %} 

{% endblock %}

photo/templates/photo/photo_detail.html
{{object}}